# Lecture 08d,  Algo: Logistic Regression

## Available libraries and differences   
[Scikit learn function and parameters](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)  

[Scikit learn user guide](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression)   

[Statsmodels](https://www.statsmodels.org/devel/discretemod.html)   
[Pingouin](https://pingouin-stats.org/generated/pingouin.logistic_regression.html)  
Other: Tensorflow 

[Different use of statsmodels and scikit-learn: stats or predictions](https://stats.stackexchange.com/a/48578)    
[Stats VS Machine Learning: complementarity and differences](https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning)

## Dataset: wikipedia, program effectiveness, iris flowers,
loaded from csv file on your disk, or from a python module. 

[Program_Effectiveness Data Source and Info](https://www.statsmodels.org/devel/datasets/generated/spector.html)   

[Program_Effectiveness Original Source and Info](https://pages.stern.nyu.edu/~wgreene/Text/econometricanalysis.htm)  

**Remember**:   
Summary about the algo:
Logistic Regression is an "supervised learning" model.
We know the labels. We have a "y" target variable. 


Goal of the algo:  
Classify instances (observations)   
Variatons:  
* binary
* multi-class
* one VS rest

Classes can be:  
* unordered (all of equal importance)   
* ordered (some classes have "more" of what defines a class.) Useful in socio-economic studies: Post Office code.   

Important notes: 
Sigmoid functions properties. Non constant "returns".   
Sigmoid functions slope.  

How much does a factor affect the result?
What will the result be?
What is the probability of the result?


In [2]:
# use pwd command to see in which folder we are working in.
# pwd means present working directory
# you may need !pwd in MacOS

In [3]:
pwd  

'C:\\Users\\tharg\\uoa_py_course\\lectures\\ipynb_files\\lecture_11_nbc_logregc\\log_res'

# A. Import the necessary modules.   
You may add libraries here as you go on with your work. But, all imports should be at the first code cell.

In [44]:
# data management libraries
import pandas as pd
import numpy as np

# visualization libraries
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import seaborn as sns

# scikit learn algo library (google it)
from sklearn.linear_model import LogisticRegression
# metrics libraries
from sklearn import metrics
from sklearn.datasets import load_iris

# import pingouin stats library
import pingouin as pg

# import statsmodels stats library
import statsmodels.api as sm

# B. Inspect the data and understand its features.   
See which are the variables, what is their type, what are the values that the variables take.  
At this step, you should think about possible relations that you ought to examine.   
Which do you think might be more important?

## The wikipedia example

In [43]:
# First, let's create the dataframe
Hours = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,
         2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]
Pass = [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]
df = pd.DataFrame({'HoursStudy': Hours, 'PassExam': Pass})

In [3]:
df.sample(4)

HoursStudy  PassExam
19        5.50         1
1         0.75         0
11        3.00         0
17        4.75         1

In [45]:
# And then run the logistic regression
X = df['HoursStudy']

In [46]:
X.sample(2)

10    2.75
18    5.00
Name: HoursStudy, dtype: float64

In [47]:
y = df['PassExam']
lr = pg.logistic_regression(X, y, penalty="l2").round(3)
lr

names   coef     se      z   pval  CI[2.5%]  CI[97.5%]
0   Intercept -3.139  1.438 -2.183  0.029    -5.958     -0.320
1  HoursStudy  1.148  0.498  2.308  0.021     0.173      2.124

In [14]:
pg.logistic_regression(X.to_numpy(), y.to_numpy(), coef_only=True, penalty="l2")

array([-3.13904399,  1.14843327])

## The program effectiveness data

In [15]:
spector_data = sm.datasets.spector.load()

In [48]:
spector_data

<class 'statsmodels.datasets.utils.Dataset'>

In [49]:
spector_data.endog

0     0.0
1     0.0
2     0.0
3     0.0
4     1.0
5     0.0
6     0.0
7     0.0
8     0.0
9     1.0
10    0.0
11    0.0
12    0.0
13    1.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    1.0
20    0.0
21    1.0
22    0.0
23    0.0
24    1.0
25    1.0
26    1.0
27    0.0
28    1.0
29    1.0
30    0.0
31    1.0
Name: GRADE, dtype: float64

In [18]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)

In [50]:
spector_data.exog

GPA  TUCE  PSI  const
0   2.66  20.0  0.0    1.0
1   2.89  22.0  0.0    1.0
2   3.28  24.0  0.0    1.0
3   2.92  12.0  0.0    1.0
4   4.00  21.0  0.0    1.0
5   2.86  17.0  0.0    1.0
6   2.76  17.0  0.0    1.0
7   2.87  21.0  0.0    1.0
8   3.03  25.0  0.0    1.0
9   3.92  29.0  0.0    1.0
10  2.63  20.0  0.0    1.0
11  3.32  23.0  0.0    1.0
12  3.57  23.0  0.0    1.0
13  3.26  25.0  0.0    1.0
14  3.53  26.0  0.0    1.0
15  2.74  19.0  0.0    1.0
16  2.75  25.0  0.0    1.0
17  2.83  19.0  0.0    1.0
18  3.12  23.0  1.0    1.0
19  3.16  25.0  1.0    1.0
20  2.06  22.0  1.0    1.0
21  3.62  28.0  1.0    1.0
22  2.89  14.0  1.0    1.0
23  3.51  26.0  1.0    1.0
24  3.54  24.0  1.0    1.0
25  2.83  27.0  1.0    1.0
26  3.39  17.0  1.0    1.0
27  2.67  24.0  1.0    1.0
28  3.65  21.0  1.0    1.0
29  4.00  23.0  1.0    1.0
30  3.10  21.0  1.0    1.0
31  2.39  19.0  1.0    1.0

In [51]:
spector_data

<class 'statsmodels.datasets.utils.Dataset'>

In [52]:
type(spector_data)

statsmodels.datasets.utils.Dataset

In [14]:
print(spector_data.exog.head())

    GPA  TUCE  PSI  const
0  2.66  20.0  0.0    1.0
1  2.89  22.0  0.0    1.0
2  3.28  24.0  0.0    1.0
3  2.92  12.0  0.0    1.0
4  4.00  21.0  0.0    1.0


In [15]:
print(spector_data.endog.head())

0    0.0
1    0.0
2    0.0
3    0.0
4    1.0
Name: GRADE, dtype: float64


In [53]:
X = pd.DataFrame(spector_data.exog)

In [54]:
y = pd.DataFrame(spector_data.endog)
y.sample(10)

GRADE
14    0.0
9     1.0
15    0.0
5     0.0
25    1.0
11    0.0
20    0.0
3     0.0
13    1.0
18    0.0

In [ ]:
logit_mod = sm.Logit(spector_data.endog, spector_data.exog)

In [22]:
logit_mod = sm.Logit(y, X)

In [55]:
logit_res = logit_mod.fit(disp=0)
print("Parameters:\n",logit_res.params)

Parameters:
 GPA       2.826113
TUCE      0.095158
PSI       2.378688
const   -13.021347
dtype: float64


In [56]:
logit_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Thu, 11 Apr 2024   Pseudo R-squ.:                  0.3740
Time:                        20:36:25   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
==============================================================================
"""

In [57]:
A = np.identity(len(logit_res.params))
A = A[1:,:]

In [58]:
logit_res.f_test(A)

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=2.8850001268853, p=0.05331525256957256, df_denom=28, df_num=3>

In [26]:
margeff = logit_res.get_margeff()
print(margeff.summary())

        Logit Marginal Effects       
Dep. Variable:                  GRADE
Method:                          dydx
At:                           overall
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            0.3626      0.109      3.313      0.001       0.148       0.577
TUCE           0.0122      0.018      0.686      0.493      -0.023       0.047
PSI            0.3052      0.092      3.304      0.001       0.124       0.486


In [60]:
print(logit_res.summary())

                           Logit Regression Results                           
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Thu, 11 Apr 2024   Pseudo R-squ.:                  0.3740
Time:                        20:36:43   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.0

In [61]:
print(logit_res.summary2())

                         Results: Logit
Model:              Logit            Method:           MLE      
Dependent Variable: GRADE            Pseudo R-squared: 0.374    
Date:               2024-04-11 20:37 AIC:              33.7793  
No. Observations:   32               BIC:              39.6422  
Df Model:           3                Log-Likelihood:   -12.890  
Df Residuals:       28               LL-Null:          -20.592  
Converged:          1.0000           LLR p-value:      0.0015019
No. Iterations:     7.0000           Scale:            1.0000   
-----------------------------------------------------------------
            Coef.    Std.Err.     z     P>|z|    [0.025    0.975]
-----------------------------------------------------------------
GPA          2.8261    1.2629   2.2377  0.0252    0.3508   5.3014
TUCE         0.0952    0.1416   0.6722  0.5014   -0.1823   0.3726
PSI          2.3787    1.0646   2.2344  0.0255    0.2922   4.4652
const      -13.0213    4.9313  -2.6405  0.00

## Iris from scikit-learn

In [87]:
dataset = load_iris()

In [88]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [91]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [90]:
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [62]:
X, y = load_iris(return_X_y=True)

### Always holdout data for testing in real life.
### in these lecture notes I performed no split of the datasets only to focus on other issues.   

In [63]:
LogisticRegression?

Init signature:
LogisticRegression(
    penalty='l2',
    *,
    dual=False,
    tol=0.0001,
    C=1.0,
    fit_intercept=True,
    intercept_scaling=1,
    class_weight=None,
    random_state=None,
    solver='lbfgs',
    max_iter=100,
    multi_class='auto',
    verbose=0,
    warm_start=False,
    n_jobs=None,
    l1_ratio=None,
)
Docstring:     
Logistic Regression (aka logit, MaxEnt) classifier.

In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
scheme if the 'multi_class' option is set to 'ovr', and uses the
cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
(Currently the 'multinomial' option is supported only by the 'lbfgs',
'sag', 'saga' and 'newton-cg' solvers.)

This class implements regularized logistic regression using the
'liblinear' library, 'newton-cg', 'sag', 'saga' and 'lbfgs' solvers. **Note
that regularization is applied by default**. It can handle both dense
and sparse input. Use C-ordered arrays or CSR matrices containi

In [76]:
clf = LogisticRegression(max_iter=200).fit(X, y)

In [67]:
clf.predict(X[:, :])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [68]:
np.set_printoptions(suppress=True)

In [69]:
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.

In [70]:
clf.score(X, y)

0.9733333333333334

In [71]:
clf.n_features_in_?

Type:        int
String form: 4
Docstring:  
int([x]) -> integer
int(x, base=10) -> integer

Convert a number or string to an integer, or return 0 if no arguments
are given.  If x is a number, return x.__int__().  For floating point
numbers, this truncates towards zero.

If x is not a number or if base is given, then x must be a string,
bytes, or bytearray instance representing an integer literal in the
given base.  The literal can be preceded by '+' or '-' and be surrounded
by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
Base 0 means to interpret the base from the string as an integer literal.
>>> int('0b100', base=0)
4

In [72]:
clf.score?

Signature: clf.score(X, y, sample_weight=None)
Docstring:
Return the mean accuracy on the given test data and labels.

In multi-label classification, this is the subset accuracy
which is a harsh metric since you require for each sample that
each label set be correctly predicted.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Test samples.

y : array-like of shape (n_samples,) or (n_samples, n_outputs)
    True labels for `X`.

sample_weight : array-like of shape (n_samples,), default=None
    Sample weights.

Returns
-------
score : float
    Mean accuracy of ``self.predict(X)`` w.r.t. `y`.
File:      ~/venv_projects/uoa_py_course/course_venv/lib/python3.11/site-packages/sklearn/base.py
Type:      method

In [73]:
# link to liblinear libary, go to datasets, phising dataset
# LogisticRegression?

clf.classes_

array([0, 1, 2])

In [74]:
clf.coef_

array([[-0.42456599,  0.96664261, -2.51554625, -1.08216927],
       [ 0.53541119, -0.32073935, -0.20740629, -0.94263206],
       [-0.1108452 , -0.64590325,  2.72295254,  2.02480133]])

In [75]:
clf.intercept_

array([  9.85494228,   2.23117432, -12.0861166 ])

In [40]:
len(clf.predict_proba(X))

150

In [41]:
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.

In [35]:
clf.score(X, y)

0.9733333333333334

In [36]:
y_pred_default = clf.predict(X)
y_pred_default

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
clf.score(X, y_pred_default)

1.0

In [38]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.3).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
clf.score(X, y_pred_tuned)

0.6533333333333333

In [40]:
# Predict confidence scores for samples.
# where > 0 means this class would be predicted.
clf.decision_function(X)

array([[  7.33564795,   3.35972702, -10.69537497],
       [  6.9367479 ,   3.41361194, -10.35035984],
       [  7.46652052,   3.26308991, -10.72961043],
       [  6.90869551,   3.20050073, -10.10919625],
       [  7.47467511,   3.27413984, -10.74881495],
       [  6.62445079,   3.14066148,  -9.76511228],
       [  7.34257956,   3.03029367, -10.37287323],
       [  7.02954126,   3.31779017, -10.34733143],
       [  7.05163707,   3.178584  , -10.23022107],
       [  6.88969492,   3.4552137 , -10.34490862],
       [  7.15038701,   3.4350796 , -10.58546662],
       [  6.86246173,   3.19026614, -10.05272786],
       [  7.08702485,   3.4545815 , -10.54160635],
       [  8.05377672,   3.24935921, -11.30313593],
       [  8.0263877 ,   3.61432601, -11.64071371],
       [  7.48446808,   3.18151707, -10.66598515],
       [  7.63132404,   3.22327079, -10.85459483],
       [  7.22769039,   3.26532161, -10.493012  ],
       [  6.50874243,   3.42752577,  -9.93626821],
       [  7.26609538,   3.14821

In [41]:
# clf?

In [42]:
clf.get_params([X])

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 200,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': 0,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [43]:
clf.n_iter_

array([122])

In [44]:
# clf.predict_log_proba(X)

In [45]:
clf.predict_proba?

Signature: clf.predict_proba(X)
Docstring:
Probability estimates.

The returned estimates for all classes are ordered by the
label of classes.

For a multi_class problem, if multi_class is set to be "multinomial"
the softmax function is used to find the predicted probability of
each class.
Else use a one-vs-rest approach, i.e calculate the probability
of each class assuming it to be positive using the logistic function.
and normalize these values across all the classes.

Parameters
----------
X : array-like of shape (n_samples, n_features)
    Vector to be scored, where `n_samples` is the number of samples and
    `n_features` is the number of features.

Returns
-------
T : array-like of shape (n_samples, n_classes)
    Returns the probability of the sample for each class in the model,
    where classes are ordered as they are in ``self.classes_``.
File:      c:\users\tharg\uoa_py_course\course_venv\lib\site-packages\sklearn\linear_model\_logistic.py
Type:      method

In [46]:
# len(clf.predict_proba(X))
clf.predict_proba(X)

array([[0.9815835 , 0.01841648, 0.00000001],
       [0.97133891, 0.02866106, 0.00000003],
       [0.98527581, 0.01472418, 0.00000001],
       [0.97606513, 0.02393483, 0.00000004],
       [0.98523375, 0.01476624, 0.00000001],
       [0.97022292, 0.02977701, 0.00000007],
       [0.98677436, 0.01322562, 0.00000002],
       [0.97614809, 0.02385188, 0.00000003],
       [0.9796288 , 0.02037117, 0.00000003],
       [0.96876492, 0.03123505, 0.00000003],
       [0.97623076, 0.02376922, 0.00000002],
       [0.97520955, 0.02479041, 0.00000004],
       [0.97423015, 0.02576982, 0.00000002],
       [0.99187311, 0.00812688, 0.        ],
       [0.98801523, 0.01198477, 0.        ],
       [0.98665199, 0.013348  , 0.00000001],
       [0.98796767, 0.01203232, 0.00000001],
       [0.9813369 , 0.01866308, 0.00000002],
       [0.9561112 , 0.04388873, 0.00000007],
       [0.98398175, 0.01601823, 0.00000002],
       [0.94617027, 0.05382965, 0.00000009],
       [0.98157531, 0.01842466, 0.00000003],
       [0.

In [47]:
clf.predict_proba(X)[:,1]

array([0.01841648, 0.02866106, 0.01472418, 0.02393483, 0.01476624,
       0.02977701, 0.01322562, 0.02385188, 0.02037117, 0.03123505,
       0.02376922, 0.02479041, 0.02576982, 0.00812688, 0.01198477,
       0.013348  , 0.01203232, 0.01866308, 0.04388873, 0.01601823,
       0.05382965, 0.01842466, 0.00403856, 0.04813798, 0.04838375,
       0.04902074, 0.03066225, 0.02535494, 0.02294806, 0.02902248,
       0.03606787, 0.03551545, 0.01170684, 0.01104235, 0.03164774,
       0.01556212, 0.02137417, 0.01325754, 0.01430161, 0.02618599,
       0.01353045, 0.03835881, 0.0110885 , 0.02777811, 0.03992287,
       0.02645912, 0.01983318, 0.01682171, 0.02164575, 0.02158452,
       0.87395335, 0.85971996, 0.72507208, 0.93969731, 0.81522397,
       0.86010558, 0.716466  , 0.84918642, 0.89664749, 0.91189229,
       0.93775038, 0.89882082, 0.97658767, 0.77924894, 0.91507518,
       0.92635028, 0.7746332 , 0.96519358, 0.80108054, 0.95944831,
       0.44006377, 0.95678422, 0.59630953, 0.85989255, 0.94295

In [48]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.4).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [49]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.4).astype(bool)
y_pred_tuned

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False,

In [50]:
preds = clf.predict_proba(X)

In [51]:
preds

array([[0.9815835 , 0.01841648, 0.00000001],
       [0.97133891, 0.02866106, 0.00000003],
       [0.98527581, 0.01472418, 0.00000001],
       [0.97606513, 0.02393483, 0.00000004],
       [0.98523375, 0.01476624, 0.00000001],
       [0.97022292, 0.02977701, 0.00000007],
       [0.98677436, 0.01322562, 0.00000002],
       [0.97614809, 0.02385188, 0.00000003],
       [0.9796288 , 0.02037117, 0.00000003],
       [0.96876492, 0.03123505, 0.00000003],
       [0.97623076, 0.02376922, 0.00000002],
       [0.97520955, 0.02479041, 0.00000004],
       [0.97423015, 0.02576982, 0.00000002],
       [0.99187311, 0.00812688, 0.        ],
       [0.98801523, 0.01198477, 0.        ],
       [0.98665199, 0.013348  , 0.00000001],
       [0.98796767, 0.01203232, 0.00000001],
       [0.9813369 , 0.01866308, 0.00000002],
       [0.9561112 , 0.04388873, 0.00000007],
       [0.98398175, 0.01601823, 0.00000002],
       [0.94617027, 0.05382965, 0.00000009],
       [0.98157531, 0.01842466, 0.00000003],
       [0.

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html?highlight=gridsearch#sklearn.model_selection.GridSearchCV

In [29]:
# https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html?highlight=grid%20search#displaying-a-grid-search-over-a-pipeline-with-a-classifier

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

pipe = Pipeline([('classifier' , LogisticRegression())])

# Create param grid.

param_grid = [
    {'classifier' : [LogisticRegression()],
     'classifier__penalty' : ['l1', 'l2'],
    'classifier__C' : np.logspace(-4, 4, 20),
    'classifier__solver' : ['liblinear']},
]

# Create grid search object

clf = GridSearchCV(pipe, param_grid = param_grid, cv = 5, verbose=True, n_jobs=-1)

# Fit on data

grid_clf = clf.fit(X, y)

Fitting 5 folds for each of 40 candidates, totalling 200 fits


In [30]:
grid_clf.score(X, y)

0.98

https://scikit-learn.org/stable/auto_examples/compose/plot_digits_pipe.html#sphx-glr-auto-examples-compose-plot-digits-pipe-py

In [54]:
grid_clf.decision_function(X)

array([[  9.73793724,  -2.35789446, -38.46549444],
       [  7.80928462,  -0.93392793, -35.51128332],
       [  8.84085257,  -1.57248307, -36.47427361],
       [  7.31275309,  -1.01546741, -34.38619375],
       [  9.98318112,  -2.61236528, -38.61948564],
       [  9.28189433,  -3.69000404, -37.12945843],
       [  8.63250221,  -2.24919731, -35.35366842],
       [  8.75091795,  -1.9304923 , -37.03242247],
       [  6.96195511,  -0.5495036 , -33.48507345],
       [  7.87190143,  -0.80471698, -36.40791923],
       [ 10.18908282,  -2.84551719, -39.67865119],
       [  8.00914255,  -1.75756096, -35.75334169],
       [  7.96704254,  -0.63654182, -36.28486302],
       [  9.08854512,  -0.91708773, -36.68970444],
       [ 13.25048828,  -4.14938259, -44.28990356],
       [ 12.39305495,  -5.39485649, -41.70572176],
       [ 11.44621513,  -4.20845804, -39.74948996],
       [  9.47983171,  -2.63362165, -37.3798783 ],
       [  9.49545119,  -3.20312387, -38.68515626],
       [  9.97552596,  -3.33239