# Lecture 12a, Logistic Regression

## Available libraries and differences   
- [Scikit learn function and parameters](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)  

- [Scikit learn user guide](https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression)   

- [Statsmodels](https://www.statsmodels.org/devel/discretemod.html)   

- [Pingouin docs](https://pingouin-stats.org/build/html/generated/pingouin.logistic_regression.html)   

- [Pingouin source code](https://pingouin-stats.org/build/html/_modules/pingouin/regression.html#logistic_regression), Check docstring, difference with scikit learn.

  > Notes
    .. caution:: This function is a wrapper around the
    :py:class:`sklearn.linear_model.LogisticRegression` class.
    However, Pingouin internally disables the L2 regularization and changes the
        default solver to 'newton-cg' to obtain results that are similar to R and
        statsmodels

- Other: TensorFlow, PyTorch.

[Different use of statsmodels and scikit-learn: stats or predictions](https://stats.stackexchange.com/a/48578)    
[Stats VS Machine Learning: complementarity and differences](https://stats.stackexchange.com/questions/6/the-two-cultures-statistics-vs-machine-learning)

## Three Datasets: wikipedia, program effectiveness, iris flowers,
Loaded from python libraries.

[Program_Effectiveness Data Source and Info](https://www.statsmodels.org/devel/datasets/generated/spector.html)   

[Program_Effectiveness Original Source and Info](https://pages.stern.nyu.edu/~wgreene/Text/econometricanalysis.htm)  

**Remember**:   
Logistic Regression is a "supervised learning" model.
We know the labels. We have a "y" target variable. 


Goal of the algo: Classify instances (observations) in different use-cases:
* binary
* multi-class
* one VS rest

Classes can be:  
* unordered: all classes of equal "quantity"(?).
* ordered: some classes have "more" of what defines a class. Useful in socio-economic studies: Post Office code.   

Important notes:   
Sigmoid functions property: Non constant "returns".   
Slope: The slope of the sigmoid function is not constant and depends on the value of the input.

How much does a factor affect the result?
What will the result be?
What is the probability of the result?

In [1]:
pwd  

'/home/tharg/venv_projects/uoa_py_course/lectures_07_12_pandas_plots_scikit/lecture_12_logistic_regression_naive_bayes_svm'

# A. Import the necessary modules.   
You may add libraries here as you go on with your work. But, all imports should be at the first code cell.

In [2]:
# data management libraries
import pandas as pd
import numpy as np

# scikit learn
from sklearn.linear_model import LogisticRegression
# metrics libraries
from sklearn import metrics
from sklearn.datasets import load_iris

# import pingouin stats library
import pingouin as pg

# import statsmodels stats library
import statsmodels.api as sm

# https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_pipeline_display.html?highlight=grid%20search#displaying-a-grid-search-over-a-pipeline-with-a-classifier

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

# B. Inspect the data and understand its features.   
See which are the variables, what is their type, what are the values that the variables take.  
At this step, you should think about possible relations that you ought to examine.   
Which do you think might be more important?

## The wikipedia example

In [3]:
# First, let's create the dataframe
Hours = [0.50, 0.75, 1.00, 1.25, 1.50, 1.75, 1.75, 2.00, 2.25, 2.50,
         2.75, 3.00, 3.25, 3.50, 4.00, 4.25, 4.50, 4.75, 5.00, 5.50]

Pass = [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1]

In [4]:
df = pd.DataFrame({'HoursStudy': Hours, 'PassExam': Pass})

In [5]:
df

,HoursStudy,PassExam
0,0.50,0
1,0.75,0
2,1.00,0
3,1.25,0
4,1.50,0
5,1.75,0
6,1.75,1
7,2.00,0
8,2.25,1
9,2.50,0


In [6]:
# X is the independent variable
X = df['HoursStudy']

In [7]:
X.sample(2)

16    4.50
3     1.25
Name: HoursStudy, dtype: float64

In [8]:
# y is the dependent variable
y = df['PassExam']

## Using logistic regression as a linear regression (example using Pingouin)

In [9]:

help(pg.logistic_regression)

Help on function logistic_regression in module pingouin.regression:

logistic_regression(X, y, coef_only=False, alpha=0.05, as_dataframe=True, remove_na=False, **kwargs)
    (Multiple) Binary logistic regression.
    
    Parameters
    ----------
    X : array_like
        Predictor(s), of shape *(n_samples, n_features)* or *(n_samples)*.
    y : array_like
        Dependent variable, of shape *(n_samples)*.
        ``y`` must be binary, i.e. only contains 0 or 1. Multinomial logistic
        regression is not supported.
    coef_only : bool
        If True, return only the regression coefficients.
    alpha : float
        Alpha value used for the confidence intervals.
        :math:`\text{CI} = [\alpha / 2 ; 1 - \alpha / 2]`
    as_dataframe : bool
        If True, returns a pandas DataFrame. If False, returns a dictionnary.
    remove_na : bool
        If True, apply a listwise deletion of missing values (i.e. the entire
        row is removed). Default is False, which will raise a

In [10]:
lr = pg.logistic_regression(X, y, penalty="l2").round(3)
lr

,names,coef,se,z,pval,CI[2.5%],CI[97.5%]
0,Intercept,-3.139,1.438,-2.183,0.029,-5.958,-0.320
1,HoursStudy,1.148,0.498,2.308,0.021,0.173,2.124


In [11]:
pg.logistic_regression(X.to_numpy(), y.to_numpy(), coef_only=True, penalty="l2")

array([-3.13904399,  1.14843327])

## The program effectiveness data

In [12]:
spector_data = sm.datasets.spector.load()

In [13]:
spector_data

<class 'statsmodels.datasets.utils.Dataset'>

In [14]:
spector_data.endog

0     0.0
1     0.0
2     0.0
3     0.0
4     1.0
5     0.0
6     0.0
7     0.0
8     0.0
9     1.0
10    0.0
11    0.0
12    0.0
13    1.0
14    0.0
15    0.0
16    0.0
17    0.0
18    0.0
19    1.0
20    0.0
21    1.0
22    0.0
23    0.0
24    1.0
25    1.0
26    1.0
27    0.0
28    1.0
29    1.0
30    0.0
31    1.0
Name: GRADE, dtype: float64

In [15]:
spector_data.exog = sm.add_constant(spector_data.exog, prepend=False)

In [16]:
spector_data.exog

,GPA,TUCE,PSI,const
0,2.66,20.0,0.0,1.0
1,2.89,22.0,0.0,1.0
2,3.28,24.0,0.0,1.0
3,2.92,12.0,0.0,1.0
4,4.00,21.0,0.0,1.0
5,2.86,17.0,0.0,1.0
6,2.76,17.0,0.0,1.0
7,2.87,21.0,0.0,1.0
8,3.03,25.0,0.0,1.0
9,3.92,29.0,0.0,1.0


In [17]:
spector_data

<class 'statsmodels.datasets.utils.Dataset'>

In [18]:
type(spector_data)

statsmodels.datasets.utils.Dataset

In [19]:
print(spector_data.exog.head())

    GPA  TUCE  PSI  const
0  2.66  20.0  0.0    1.0
1  2.89  22.0  0.0    1.0
2  3.28  24.0  0.0    1.0
3  2.92  12.0  0.0    1.0
4  4.00  21.0  0.0    1.0


In [20]:
print(spector_data.endog.head())

0    0.0
1    0.0
2    0.0
3    0.0
4    1.0
Name: GRADE, dtype: float64


In [21]:
X = pd.DataFrame(spector_data.exog)

In [22]:
X

,GPA,TUCE,PSI,const
0,2.66,20.0,0.0,1.0
1,2.89,22.0,0.0,1.0
2,3.28,24.0,0.0,1.0
3,2.92,12.0,0.0,1.0
4,4.00,21.0,0.0,1.0
5,2.86,17.0,0.0,1.0
6,2.76,17.0,0.0,1.0
7,2.87,21.0,0.0,1.0
8,3.03,25.0,0.0,1.0
9,3.92,29.0,0.0,1.0


In [23]:
y = pd.DataFrame(spector_data.endog)
y.sample(10)

,GRADE
19,1.0
30,0.0
21,1.0
18,0.0
6,0.0
27,0.0
29,1.0
7,0.0
3,0.0
1,0.0


## Using logistic regression as a linear regression (example using Statsmodels)

In [24]:
logit_mod = sm.Logit(spector_data.endog, spector_data.exog)

In [25]:
logit_mod = sm.Logit(y, X)

In [26]:
#results = logit_mod.fit()
logit_res = logit_mod.fit(disp=0)
print("Parameters:\n",logit_res.params)

Parameters:
 GPA       2.826113
TUCE      0.095158
PSI       2.378688
const   -13.021347
dtype: float64


In [27]:

help(logit_res)

Help on BinaryResultsWrapper in module statsmodels.discrete.discrete_model:

<statsmodels.discrete.discrete_model.BinaryResultsWrapper object>
    A results class for Logit Model
    
    Parameters
    ----------
    model : A DiscreteModel instance
    params : array_like
        The parameters of a fitted model.
    hessian : array_like
        The hessian of the fitted model.
    scale : float
        A scale parameter for the covariance matrix.
    
    Attributes
    ----------
    df_resid : float
        See model definition.
    df_model : float
        See model definition.
    llf : float
        Value of the loglikelihood



In [28]:
logit_res.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Tue, 27 May 2025   Pseudo R-squ.:                  0.3740
Time:                        15:20:06   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.025       0.292       4.465
const        -13.0213      4.931     -2.641      0.008     -22.687      -3.356
==============================================================================
"""

In [29]:
A = np.identity(len(logit_res.params))
A = A[1:,:]

In [30]:
logit_res.f_test(A)

<class 'statsmodels.stats.contrast.ContrastResults'>
<F test: F=2.8850001268853, p=0.05331525256957256, df_denom=28, df_num=3>

In [31]:
margeff = logit_res.get_margeff()
print(margeff.summary())

        Logit Marginal Effects       
Dep. Variable:                  GRADE
Method:                          dydx
At:                           overall
                dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            0.3626      0.109      3.313      0.001       0.148       0.577
TUCE           0.0122      0.018      0.686      0.493      -0.023       0.047
PSI            0.3052      0.092      3.304      0.001       0.124       0.486


In [32]:
print(logit_res.summary())

                           Logit Regression Results                           
Dep. Variable:                  GRADE   No. Observations:                   32
Model:                          Logit   Df Residuals:                       28
Method:                           MLE   Df Model:                            3
Date:                Tue, 27 May 2025   Pseudo R-squ.:                  0.3740
Time:                        15:20:06   Log-Likelihood:                -12.890
converged:                       True   LL-Null:                       -20.592
Covariance Type:            nonrobust   LLR p-value:                  0.001502
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
GPA            2.8261      1.263      2.238      0.025       0.351       5.301
TUCE           0.0952      0.142      0.672      0.501      -0.182       0.373
PSI            2.3787      1.065      2.234      0.0

In [33]:
print(logit_res.summary2())

                         Results: Logit
Model:              Logit            Method:           MLE      
Dependent Variable: GRADE            Pseudo R-squared: 0.374    
Date:               2025-05-27 15:20 AIC:              33.7793  
No. Observations:   32               BIC:              39.6422  
Df Model:           3                Log-Likelihood:   -12.890  
Df Residuals:       28               LL-Null:          -20.592  
Converged:          1.0000           LLR p-value:      0.0015019
No. Iterations:     7.0000           Scale:            1.0000   
-----------------------------------------------------------------
            Coef.    Std.Err.     z     P>|z|    [0.025    0.975]
-----------------------------------------------------------------
GPA          2.8261    1.2629   2.2377  0.0252    0.3508   5.3014
TUCE         0.0952    0.1416   0.6722  0.5014   -0.1823   0.3726
PSI          2.3787    1.0646   2.2344  0.0255    0.2922   4.4652
const      -13.0213    4.9313  -2.6405  0.00

## Iris from scikit-learn

In [34]:
dataset = load_iris()

In [35]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [36]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
dataset.data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [38]:
X, y = load_iris(return_X_y=True)

In [39]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

### Always holdout data for testing in real life.
### in these lecture notes I performed no split of the datasets only to focus on other issues.   

In [40]:
help(LogisticRegression)

Help on class LogisticRegression in module sklearn.linear_model._logistic:

class LogisticRegression(sklearn.linear_model._base.LinearClassifierMixin, sklearn.linear_model._base.SparseCoefMixin, sklearn.base.BaseEstimator)
 |  LogisticRegression(penalty='l2', *, dual=False, tol=0.0001, C=1.0, fit_intercept=True, intercept_scaling=1, class_weight=None, random_state=None, solver='lbfgs', max_iter=100, multi_class='auto', verbose=0, warm_start=False, n_jobs=None, l1_ratio=None)
 |  
 |  Logistic Regression (aka logit, MaxEnt) classifier.
 |  
 |  In the multiclass case, the training algorithm uses the one-vs-rest (OvR)
 |  scheme if the 'multi_class' option is set to 'ovr', and uses the
 |  cross-entropy loss if the 'multi_class' option is set to 'multinomial'.
 |  (Currently the 'multinomial' option is supported only by the 'lbfgs',
 |  'sag', 'saga' and 'newton-cg' solvers.)
 |  
 |  This class implements regularized logistic regression using the
 |  'liblinear' library, 'newton-cg', 's

In [41]:
clf = LogisticRegression(max_iter=400, solver='lbfgs', penalty='l2')

In [42]:

clf

LogisticRegression(max_iter=400)

In [43]:
clf = LogisticRegression(max_iter=400).fit(X, y)

In [44]:

clf

LogisticRegression(max_iter=400)

In [45]:
clf.predict(X[:, :])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [46]:

clf

LogisticRegression(max_iter=400)

In [47]:
np.set_printoptions(suppress=True)

In [48]:
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.

In [49]:
clf.score(X, y)

0.9733333333333334

In [50]:
clf.n_features_in_

4

In [51]:
# link to liblinear libary, go to datasets, phising dataset
# LogisticRegression?

clf.classes_

array([0, 1, 2])

In [52]:
clf.coef_

array([[-0.42456599,  0.96664261, -2.51554625, -1.08216927],
       [ 0.53541119, -0.32073935, -0.20740629, -0.94263206],
       [-0.1108452 , -0.64590325,  2.72295254,  2.02480133]])

In [53]:
clf.intercept_

array([  9.85494228,   2.23117432, -12.0861166 ])

In [54]:
len(clf.predict_proba(X))

150

In [55]:
clf.score(X, y)

0.9733333333333334

In [56]:
y_pred_default = clf.predict(X)
y_pred_default

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [57]:
clf.score(X, y_pred_default)

1.0

In [58]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.3).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [59]:
clf.score(X, y_pred_tuned)

0.6533333333333333

In [60]:
# Predict confidence scores for samples.
# where > 0 means this class would be predicted.
clf.decision_function(X)

array([[  7.33470626,   3.36028842, -10.69499468],
       [  6.93629815,   3.41357586, -10.34987401],
       [  7.4660945 ,   3.26308638, -10.72918088],
       [  6.90877759,   3.20013794, -10.10891552],
       [  7.47382712,   3.27467337, -10.74850048],
       [  6.62289578,   3.14186774,  -9.76476351],
       [  7.34210807,   3.03039356, -10.37250162],
       [  7.02894397,   3.31808061, -10.34702458],
       [  7.05191689,   3.1779442 , -10.22986109],
       [  6.88962472,   3.4550245 , -10.34464922],
       [  7.14911036,   3.43602328, -10.58513364],
       [  6.86230254,   3.19025774, -10.05256029],
       [  7.08697168,   3.45429795, -10.54126963],
       [  8.05391855,   3.24881424, -11.30273279],
       [  8.02394062,   3.61618783, -11.64012845],
       [  7.48195653,   3.18360267, -10.66555921],
       [  7.62911428,   3.22483025, -10.85394453],
       [  7.22648933,   3.26602521, -10.49251455],
       [  6.50707865,   3.42882823,  -9.93590688],
       [  7.26492749,   3.14906

In [61]:
# clf?

In [62]:
clf.get_params([X])

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 400,
 'multi_class': 'auto',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [63]:
clf.n_iter_

array([109], dtype=int32)

In [64]:
# clf.predict_log_proba(X)

In [65]:
clf.predict_proba?

In [66]:
# len(clf.predict_proba(X))
clf.predict_proba(X)

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.

In [67]:
clf.predict_proba(X)[:,1]

array([0.01844368, 0.02867258, 0.01473031, 0.02392443, 0.01478635,
       0.02985689, 0.01323307, 0.02387256, 0.02035283, 0.03123145,
       0.0238208 , 0.02479405, 0.02576404, 0.00812135, 0.0120359 ,
       0.01340868, 0.01207721, 0.01869799, 0.04401337, 0.01605002,
       0.05389863, 0.01846623, 0.00404427, 0.0482164 , 0.04835589,
       0.04902783, 0.03070504, 0.02539188, 0.02298451, 0.02901308,
       0.03606051, 0.03560671, 0.01172788, 0.01107866, 0.0316564 ,
       0.01558361, 0.02143125, 0.01326719, 0.01429391, 0.02621482,
       0.01355602, 0.03833119, 0.01108516, 0.027842  , 0.03997691,
       0.02647387, 0.01985967, 0.01682052, 0.02168768, 0.02160605,
       0.87407819, 0.85981231, 0.72525793, 0.93964232, 0.81527699,
       0.86006552, 0.71662283, 0.8489463 , 0.89669226, 0.91183771,
       0.93760263, 0.89884805, 0.97656642, 0.77926874, 0.91513279,
       0.92641289, 0.77461592, 0.96516591, 0.80099624, 0.95941064,
       0.44016173, 0.95680135, 0.59626649, 0.85988459, 0.94298

In [68]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.8).astype(int)
y_pred_tuned

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [69]:
y_pred_tuned = (clf.predict_proba(X)[:,1] >= 0.4).astype(bool)
y_pred_tuned

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True, False, False, False, False, False, False,
        True, False,

In [70]:
preds = clf.predict_proba(X)

In [71]:
preds

array([[0.98155631, 0.01844368, 0.00000001],
       [0.97132739, 0.02867258, 0.00000003],
       [0.98526968, 0.01473031, 0.00000001],
       [0.97607553, 0.02392443, 0.00000004],
       [0.98521363, 0.01478635, 0.00000001],
       [0.97014304, 0.02985689, 0.00000007],
       [0.98676691, 0.01323307, 0.00000002],
       [0.97612741, 0.02387256, 0.00000003],
       [0.97964714, 0.02035283, 0.00000003],
       [0.96876852, 0.03123145, 0.00000003],
       [0.97617918, 0.0238208 , 0.00000002],
       [0.9752059 , 0.02479405, 0.00000004],
       [0.97423594, 0.02576404, 0.00000002],
       [0.99187865, 0.00812135, 0.        ],
       [0.9879641 , 0.0120359 , 0.        ],
       [0.98659131, 0.01340868, 0.00000001],
       [0.98792278, 0.01207721, 0.00000001],
       [0.98130199, 0.01869799, 0.00000002],
       [0.95598656, 0.04401337, 0.00000007],
       [0.98394996, 0.01605002, 0.00000002],
       [0.94610128, 0.05389863, 0.00000009],
       [0.98153374, 0.01846623, 0.00000003],
       [0.

https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html?highlight=gridsearch#sklearn.model_selection.GridSearchCV

# Pipeline and GridSearchCV example

In [72]:

pipeline_instance = Pipeline([('classifier' , LogisticRegression())])

# Create param grid, 40 combinations of parameters
param_grid = [

SyntaxError: incomplete input (2244462395.py, line 4)

In [147]:
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

# Update pipeline instance with a placeholder for multiple classifiers
pipeline_instance = Pipeline([('classifier', LogisticRegression())])

# Update param grid with additional classifiers and their hyperparameters
param_grid = [
    # Logistic Regression parameters
    {'classifier': [LogisticRegression(max_iter=10000)],
     'classifier__penalty': ['l1', 'l2'],
     'classifier__C': np.logspace(-4, 4, 20),
     'classifier__solver': ['liblinear', 'saga']},

    # SVC parameters
    {'classifier': [SVC()],
     'classifier__C': [0.1, 1, 10, 100],
     'classifier__kernel': ['linear', 'rbf']},

    # Random Forest parameters
    {'classifier': [RandomForestClassifier()],
     'classifier__n_estimators': [10, 50, 100],
     'classifier__max_depth': [None, 10, 20, 30]}
]

# Create grid search object
clf = GridSearchCV(pipeline_instance, param_grid=param_grid, cv=5, verbose=True, n_jobs=3)

# Fit on data
grid_clf = clf.fit(X, y)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


In [148]:
grid_clf.score(X, y)

0.98

In [149]:

grid_clf.best_estimator_

Pipeline(steps=[('classifier',
                 LogisticRegression(C=1.623776739188721, max_iter=10000,
                                    penalty='l1', solver='saga'))])

In [80]:
grid_clf.cv_results_

{'mean_fit_time': array([0.00076461, 0.00082331, 0.00097885, 0.00151606, 0.00074215,
        0.00088644, 0.00070205, 0.00169353, 0.00069695, 0.00093532,
        0.00081773, 0.00134239, 0.00062189, 0.00083241, 0.00069809,
        0.00240178, 0.00070682, 0.00094628, 0.00087762, 0.00358243,
        0.00070343, 0.00184202, 0.00066614, 0.00624175, 0.00078788,
        0.00436406, 0.00071387, 0.01348271, 0.00200453, 0.01701536,
        0.00083351, 0.02095718, 0.00346575, 0.03941498, 0.00086436,
        0.03130474, 0.00635819, 0.08497725, 0.0009057 , 0.04718671,
        0.00806899, 0.04089236, 0.00089941, 0.0422585 , 0.00919061,
        0.07637062, 0.00094509, 0.02497091, 0.01154122, 0.06979895,
        0.00097179, 0.01576576, 0.01019516, 0.06376667, 0.0009891 ,
        0.02439318, 0.01183958, 0.0583849 , 0.00144525, 0.03547692,
        0.01513295, 0.06286492, 0.00106711, 0.04376392, 0.01400261,
        0.06434679, 0.00120392, 0.04692259, 0.01378651, 0.06979203,
        0.00112123, 0.05196033,

In [150]:
# convert the results to a DataFrame
results_df = pd.DataFrame(grid_clf.cv_results_)
results_df


,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_classifier__penalty,param_classifier__solver,param_classifier__kernel,param_classifier__max_depth,param_classifier__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001344,0.000131,0.000631,0.000046,LogisticRegression(max_iter=10000),0.0001,l1,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
1,0.001191,0.000117,0.000521,0.000037,LogisticRegression(max_iter=10000),0.0001,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
2,0.001013,0.000127,0.000491,0.000023,LogisticRegression(max_iter=10000),0.0001,l2,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
3,0.002180,0.000157,0.000527,0.000022,LogisticRegression(max_iter=10000),0.0001,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.700000,0.700000,0.666667,0.666667,0.666667,0.680000,0.016330,81
4,0.000818,0.000032,0.000446,0.000009,LogisticRegression(max_iter=10000),0.000264,l1,liblinear,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.333333,0.333333,0.333333,0.333333,0.333333,0.333333,0.000000,87
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.027042,0.000423,0.001130,0.000041,RandomForestClassifier(),NaN,NaN,NaN,NaN,20,50,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.933333,0.900000,1.000000,0.953333,0.033993,56
96,0.054905,0.001659,0.001983,0.000096,RandomForestClassifier(),NaN,NaN,NaN,NaN,20,100,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.933333,0.966667,1.000000,0.966667,0.021082,31
97,0.006245,0.000074,0.000548,0.000005,RandomForestClassifier(),NaN,NaN,NaN,NaN,30,10,"{'classifier': RandomForestClassifier(), 'clas...",0.933333,0.966667,0.900000,0.966667,1.000000,0.953333,0.033993,56
98,0.028352,0.000582,0.001185,0.000051,RandomForestClassifier(),NaN,NaN,NaN,NaN,30,50,"{'classifier': RandomForestClassifier(), 'clas...",0.966667,0.966667,0.900000,0.933333,1.000000,0.953333,0.033993,56


In [151]:
# get the top 5 results
top_5_results = results_df.nlargest(5, 'mean_test_score')
top_5_results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_classifier,param_classifier__C,param_classifier__penalty,param_classifier__solver,param_classifier__kernel,param_classifier__max_depth,param_classifier__n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
41,0.021802,0.002927,0.000283,0.000025,LogisticRegression(max_iter=10000),1.623777,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
43,0.027774,0.003591,0.000279,0.000019,LogisticRegression(max_iter=10000),1.623777,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,0.966667,1.0,0.966667,0.966667,1.0,0.98,0.016330,1
45,0.040159,0.001160,0.000333,0.000030,LogisticRegression(max_iter=10000),4.281332,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
47,0.013126,0.002071,0.000270,0.000009,LogisticRegression(max_iter=10000),4.281332,l2,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1
49,0.032871,0.005226,0.000318,0.000057,LogisticRegression(max_iter=10000),11.288379,l1,saga,NaN,NaN,NaN,{'classifier': LogisticRegression(max_iter=100...,1.000000,1.0,0.966667,0.933333,1.0,0.98,0.026667,1


In [152]:
# get the best parameters
best_params = grid_clf.best_params_
best_params

{'classifier': LogisticRegression(max_iter=10000),
 'classifier__C': 1.623776739188721,
 'classifier__penalty': 'l1',
 'classifier__solver': 'saga'}

In [153]:
# The values 9.737937, -2.357894, -38.465492 are the decision scores for a single sample across three classes (e.g., class 0, class 1, and class 2).
# The class with the highest score is the predicted class for that sample.
grid_clf.decision_function(X)

array([[ 9.67367710e+00,  4.11078015e+00, -1.58436460e+01],
       [ 8.13704208e+00,  4.11078015e+00, -1.46076839e+01],
       [ 9.06235192e+00,  4.11078015e+00, -1.50153107e+01],
       [ 8.13371325e+00,  4.11078015e+00, -1.39215255e+01],
       [ 9.98100410e+00,  4.11078015e+00, -1.58604913e+01],
       [ 9.97101761e+00,  4.11078015e+00, -1.49030333e+01],
       [ 9.36635009e+00,  4.11078015e+00, -1.43206384e+01],
       [ 9.05569426e+00,  4.11078015e+00, -1.51237971e+01],
       [ 7.82971508e+00,  4.11078015e+00, -1.36036365e+01],
       [ 8.13371325e+00,  4.11078015e+00, -1.49340868e+01],
       [ 9.97767527e+00,  4.11078015e+00, -1.63260687e+01],
       [ 8.74503843e+00,  4.11078015e+00, -1.44207934e+01],
       [ 8.13704208e+00,  4.11078015e+00, -1.49621105e+01],
       [ 9.06900958e+00,  4.11078015e+00, -1.52612511e+01],
       [ 1.18316238e+01,  4.11078015e+00, -1.86501492e+01],
       [ 1.21289643e+01,  4.11078015e+00, -1.70514018e+01],
       [ 1.12136409e+01,  4.11078015e+00